# Generated by Django 4.2.5 on 2025-05-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='imageField',
            new_name='image',
        ),
    ]
